"use client";

import { useState, useTransition, type FormEvent } from "react";
import { Plus, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { FormSwitch } from "@/components/ui/form-switch";
import { Input } from "@/components/ui/input";
import {
  deleteAchievement, deleteChallenge, deleteLevel, saveAchievement, saveChallenge,
  saveGamificationRule, saveLevel, updateProtectorMax, type GamificationActionResult,
} from "@/lib/actions/gamification";
import type { AdminGamificationData, LevelItem } from "@/lib/data/gamification";

const field = "min-h-11 w-full rounded-lg border border-input bg-white px-3 text-base";
const label = "space-y-1 text-sm font-semibold text-choco-600";

function Check({ name, defaultChecked, text, disabled = false }: { name: string; defaultChecked?: boolean; text: string; disabled?: boolean }) {
  return <FormSwitch name={name} defaultChecked={defaultChecked} label={text} disabled={disabled} />;
}

function SubmitForm({ children, onSubmit }: { children: React.ReactNode; onSubmit: (formData: FormData) => void }) {
  return <form className="grid gap-3" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); onSubmit(new FormData(event.currentTarget)); }}>{children}</form>;
}

function LevelEditor({ level, submit, remove, busy }: { level?: LevelItem; submit: (data: FormData) => void; remove?: () => void; busy: boolean }) {
  return <details open={!level} className="rounded-xl border border-cream-200 bg-white p-3"><summary className="cursor-pointer font-display text-lg font-bold">{level ? `${level.icon} Nivel ${level.number} · ${level.name}` : "➕ Nuevo nivel"}</summary><div className="mt-3"><SubmitForm onSubmit={submit}><input type="hidden" name="id" value={level?.id ?? ""} /><div className="grid grid-cols-2 gap-3"><label className={label}>Número<Input name="number" inputMode="numeric" defaultValue={level?.number ?? ""} required /></label><label className={label}>XP requerido<Input name="xpRequired" inputMode="numeric" defaultValue={level?.xpRequired ?? ""} required /></label></div><div className="grid grid-cols-[5rem_1fr] gap-3"><label className={label}>Icono<Input name="icon" defaultValue={level?.icon ?? "⭐"} required /></label><label className={label}>Nombre<Input name="name" defaultValue={level?.name ?? ""} required /></label></div><label className={label}>Descripción<textarea name="description" defaultValue={level?.description ?? ""} className={`${field} min-h-20 py-2`} /></label><label className={label}>Beneficio opcional<Input name="benefit" defaultValue={level?.benefit ?? ""} /></label><Check name="active" defaultChecked={level?.active ?? true} text="Nivel activo" /><div className="flex flex-col gap-2 sm:flex-row"><Button disabled={busy} type="submit"><Save /> Guardar nivel</Button>{remove ? <Button disabled={busy} type="button" variant="destructive" onClick={remove}><Trash2 /> Eliminar</Button> : null}</div></SubmitForm></div></details>;
}

function AchievementEditor({ item, products, submit, remove, busy }: { item?: AdminGamificationData["achievements"][number]; products: AdminGamificationData["products"]; submit: (data: FormData) => void; remove?: () => void; busy: boolean }) {
  const [condition, setCondition] = useState(item?.conditionType ?? "TOTAL_SALES");
  return <details open={!item} className="rounded-xl border border-cream-200 bg-white p-3"><summary className="cursor-pointer font-display text-lg font-bold">{item ? `${item.icon} ${item.name}` : "➕ Nuevo logro"}</summary><div className="mt-3"><SubmitForm onSubmit={submit}><input type="hidden" name="id" value={item?.id ?? ""} /><div className="grid grid-cols-[5rem_1fr] gap-3"><label className={label}>Icono<Input name="icon" defaultValue={item?.icon ?? "🏅"} required /></label><label className={label}>Nombre<Input name="name" defaultValue={item?.name ?? ""} required /></label></div><label className={label}>Código estable<Input name="code" defaultValue={item?.code ?? ""} placeholder="PRIMERA_VENTA" required /></label><label className={label}>Descripción<textarea name="description" defaultValue={item?.description ?? ""} className={`${field} min-h-20 py-2`} /></label><div className="grid gap-3 sm:grid-cols-2"><label className={label}>Condición<select name="conditionType" value={condition} onChange={(event) => setCondition(event.target.value)} className={field}>{[["TOTAL_SALES","Ventas totales"],["TOTAL_UNITS","Unidades totales"],["TOTAL_PROFIT","Ganancia propia"],["STREAK_DAYS","Mejor racha"],["PRODUCT_UNITS","Unidades de producto"],["GOALS_COMPLETED","Metas completadas"]].map(([value,text]) => <option key={value} value={value}>{text}</option>)}</select></label><label className={label}>Valor objetivo<Input name="targetValue" inputMode="decimal" defaultValue={item?.targetValue ?? ""} required /></label></div>{condition === "PRODUCT_UNITS" ? <label className={label}>Producto<select name="productId" defaultValue={item?.productId ?? ""} className={field} required><option value="">Selecciona</option>{products.map((product) => <option key={product.id} value={product.id}>{product.emoji} {product.name}</option>)}</select></label> : null}<div className="grid grid-cols-3 gap-3"><label className={label}>XP<Input name="xpReward" inputMode="numeric" defaultValue={item?.xpReward ?? 0} required /></label><label className={label}>Puntos<Input name="pointsReward" inputMode="numeric" defaultValue={item?.pointsReward ?? 0} required /></label><label className={label}>Orden<Input name="sortOrder" inputMode="numeric" defaultValue={item?.sortOrder ?? 0} required /></label></div><div className="grid sm:grid-cols-2"><Check name="hidden" defaultChecked={item?.hidden} text="Logro secreto" /><Check name="active" defaultChecked={item?.active ?? true} text="Logro activo" /></div><div className="flex flex-col gap-2 sm:flex-row"><Button disabled={busy} type="submit"><Save /> Guardar logro</Button>{remove ? <Button disabled={busy} type="button" variant="destructive" onClick={remove}><Trash2 /> Eliminar</Button> : null}</div></SubmitForm></div></details>;
}

function ChallengeEditor({ item, products, today, submit, remove, busy }: { item?: AdminGamificationData["challenges"][number]; products: AdminGamificationData["products"]; today: string; submit: (data: FormData) => void; remove?: () => void; busy: boolean }) {
  const [condition, setCondition] = useState(item?.conditionType ?? "UNITS_SOLD");
  return <details open={!item} className="rounded-xl border border-cream-200 bg-white p-3"><summary className="cursor-pointer font-display text-lg font-bold">{item ? `${item.icon} ${item.name}` : "➕ Nuevo reto"}</summary><div className="mt-3"><SubmitForm onSubmit={submit}><input type="hidden" name="id" value={item?.id ?? ""} /><div className="grid grid-cols-[5rem_1fr] gap-3"><label className={label}>Icono<Input name="icon" defaultValue={item?.icon ?? "🎯"} required /></label><label className={label}>Nombre<Input name="name" defaultValue={item?.name ?? ""} required /></label></div><label className={label}>Descripción<textarea name="description" defaultValue={item?.description ?? ""} className={`${field} min-h-20 py-2`} /></label><div className="grid grid-cols-2 gap-3"><label className={label}>Inicia<Input name="startsOn" type="date" defaultValue={item?.startsOn ?? today} required /></label><label className={label}>Termina<Input name="endsOn" type="date" defaultValue={item?.endsOn ?? today} required /></label></div><div className="grid gap-3 sm:grid-cols-2"><label className={label}>Condición<select name="conditionType" value={condition} onChange={(event) => setCondition(event.target.value)} className={field}>{[["SALES_COUNT","Cantidad de ventas"],["UNITS_SOLD","Unidades vendidas"],["PROFIT_AMOUNT","Ganancia propia"],["ACTIVE_DAYS","Días activos"],["PRODUCT_UNITS","Unidades de producto"]].map(([value,text]) => <option key={value} value={value}>{text}</option>)}</select></label><label className={label}>Valor objetivo<Input name="targetValue" inputMode="decimal" defaultValue={item?.targetValue ?? ""} required /></label></div>{condition === "PRODUCT_UNITS" ? <label className={label}>Producto<select name="productId" defaultValue={item?.productId ?? ""} className={field} required><option value="">Selecciona</option>{products.map((product) => <option key={product.id} value={product.id}>{product.emoji} {product.name}</option>)}</select></label> : null}<div className="grid grid-cols-3 gap-3"><label className={label}>XP<Input name="xpReward" inputMode="numeric" defaultValue={item?.xpReward ?? 0} required /></label><label className={label}>Puntos<Input name="pointsReward" inputMode="numeric" defaultValue={item?.pointsReward ?? 0} required /></label><label className={label}>Estado<select name="status" defaultValue={item?.status ?? "DRAFT"} className={field}><option value="DRAFT">Borrador</option><option value="ACTIVE">Activo</option><option value="FINISHED">Finalizado</option></select></label></div><div className="flex flex-col gap-2 sm:flex-row"><Button disabled={busy} type="submit"><Save /> Guardar reto</Button>{remove ? <Button disabled={busy} type="button" variant="destructive" onClick={remove}><Trash2 /> Eliminar</Button> : null}</div></SubmitForm></div></details>;
}

export function GamificationManager({ data }: { data: AdminGamificationData }) {
  const [busy, startTransition] = useTransition();
  const run = (action: () => Promise<GamificationActionResult>) => startTransition(async () => {
    const result = await action();
    if (result.status === "success") toast.success(result.message);
    else toast.error(result.message);
  });
  return <div className="space-y-7">
    <section className="rounded-card border border-cream-200 bg-cream-50 p-4 shadow-soft"><h2 className="font-display text-2xl font-bold">Reglas por venta</h2><p className="mb-4 text-sm text-choco-600">Los cambios se aplican únicamente a ventas futuras.</p><div className="space-y-3">{data.rules.map((rule) => <SubmitForm key={rule.id} onSubmit={(form) => run(() => saveGamificationRule(form))}><input type="hidden" name="event" value={rule.event} /><div className="grid grid-cols-2 gap-3 sm:grid-cols-[1fr_8rem_8rem_auto]"><div><p className="font-bold">{rule.event === "SALE_COMPLETED" ? "Venta completada" : "Cada unidad vendida"}</p><p className="text-xs text-choco-600">{rule.event}</p></div><label className={label}>XP<Input name="xpAmount" inputMode="numeric" defaultValue={rule.xpAmount} /></label><label className={label}>Puntos<Input name="pointsAmount" inputMode="numeric" defaultValue={rule.pointsAmount} /></label><Check name="active" defaultChecked={rule.active} text="Activa" /></div><Button disabled={busy} type="submit" variant="outline"><Save /> Guardar regla</Button></SubmitForm>)}</div></section>
    <section className="rounded-card border border-cream-200 bg-cream-50 p-4 shadow-soft"><h2 className="font-display text-2xl font-bold">Protectores</h2><p className="text-sm text-choco-600">Cada niño recibe 3 gratuitos y puede reponer los consumidos sin superar este límite.</p><SubmitForm onSubmit={(form) => run(() => updateProtectorMax(form))}><label className={label}>Límite por niño (máximo 3)<Input className="max-w-40" name="protectorMax" inputMode="numeric" min="0" max="3" defaultValue={data.protectorMax} /></label><Button disabled={busy} className="w-fit" type="submit"><Save /> Guardar límite</Button></SubmitForm></section>
    <section><div className="mb-3 flex items-center gap-2"><Plus className="size-5 text-xp-500" /><h2 className="font-display text-2xl font-bold">Niveles</h2></div><div className="space-y-3">{data.levels.map((item) => <LevelEditor key={item.id} level={item} busy={busy} submit={(form) => run(() => saveLevel(form))} remove={() => run(() => deleteLevel(item.id))} />)}<LevelEditor busy={busy} submit={(form) => run(() => saveLevel(form))} /></div></section>
    <section><h2 className="mb-3 font-display text-2xl font-bold">Logros</h2><div className="space-y-3">{data.achievements.map((item) => <AchievementEditor key={item.id} item={item} products={data.products} busy={busy} submit={(form) => run(() => saveAchievement(form))} remove={() => run(() => deleteAchievement(item.id))} />)}<AchievementEditor products={data.products} busy={busy} submit={(form) => run(() => saveAchievement(form))} /></div></section>
    <section><h2 className="mb-3 font-display text-2xl font-bold">Retos</h2><div className="space-y-3">{data.challenges.map((item) => <ChallengeEditor key={item.id} item={item} products={data.products} today={data.today} busy={busy} submit={(form) => run(() => saveChallenge(form))} remove={() => run(() => deleteChallenge(item.id))} />)}<ChallengeEditor products={data.products} today={data.today} busy={busy} submit={(form) => run(() => saveChallenge(form))} /></div></section>
  </div>;
}
