import { ArrowLeft, Banknote, CircleDollarSign, PackageCheck, ReceiptText, Smartphone, Users } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

import { StatCard } from "@/components/shared";
import { buttonVariants } from "@/components/ui/button";
import { requireParent } from "@/lib/auth/guards";
import { getAdminSaleDetail } from "@/lib/data/stats";
import { formatCOP } from "@/lib/domain/money";

export default async function AdminSaleDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requireParent();
  const detail = await getAdminSaleDetail((await params).id);
  if (!detail) notFound();
  const { sale } = detail;
  return <main className="mx-auto w-full max-w-5xl px-4 py-6 pb-12 text-choco-800"><header className="mb-5 flex items-center gap-3"><Link href="/admin/ventas" className={buttonVariants({ variant: "ghost", size: "icon" })} aria-label="Volver al historial"><ArrowLeft /></Link><div className="min-w-0"><p className="text-sm font-semibold text-caramel-600">Venta #{sale.id.slice(0, 8).toUpperCase()}</p><h1 className="font-display text-3xl font-bold">Detalle de venta</h1></div></header>
    <section className={`rounded-card border p-5 shadow-soft ${sale.status === "VOIDED" ? "border-danger-500/30 bg-danger-500/5" : "border-cream-200 bg-cream-50"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-display text-xl font-bold">{sale.sellerEmoji} {sale.sellerName}</p><p className="text-sm text-choco-600">{new Intl.DateTimeFormat("es-CO", { dateStyle: "full", timeStyle: "short" }).format(new Date(sale.soldAt))}</p></div><span className={`rounded-full px-3 py-1 text-sm font-bold ${sale.status === "COMPLETED" ? "bg-success-500/10 text-success-500" : "bg-danger-500/10 text-danger-500"}`}>{sale.status === "COMPLETED" ? "Completada" : "Anulada"}</span></div>{sale.status === "VOIDED" ? <p className="mt-3 rounded-xl bg-white/70 p-3 text-sm"><strong>Motivo:</strong> {sale.voidReason ?? "Sin motivo registrado"}</p> : null}</section>
    <section className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4"><StatCard icon={<ReceiptText className="size-5 text-caramel-600" />} label="Total vendido" value={formatCOP(sale.itemsTotal)} /><StatCard icon={<PackageCheck className="size-5 text-goal-500" />} label="Unidades" value={String(sale.unitsTotal)} /><StatCard icon={<Banknote className="size-5 text-choco-600" />} label="Costo" value={formatCOP(Math.round(sale.costTotal))} /><StatCard icon={<CircleDollarSign className="size-5 text-success-500" />} label="Ganancia total" value={formatCOP(sale.earningsTotal)} detail={`Margen ${formatCOP(sale.marginTotal)} + propina ${formatCOP(sale.tipTotal)}`} /></section>
    <section className="mt-6 rounded-card border border-cream-200 bg-cream-50 p-4 shadow-soft"><h2 className="font-display text-2xl font-bold">Pago</h2><div className="mt-3 flex items-center gap-2 font-bold">{sale.paymentMethod === "CASH" ? <Banknote className="size-5" /> : <Smartphone className="size-5" />}{sale.paymentMethod === "CASH" ? "Efectivo" : "Transferencia"}</div>{sale.paymentMethod === "CASH" ? <dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-choco-600">Recibido</dt><dd className="font-bold">{formatCOP(sale.cashReceived ?? 0)}</dd></div><div><dt className="text-choco-600">Cambio entregado</dt><dd className="font-bold">{formatCOP(sale.changeGiven ?? 0)}</dd></div></dl> : null}{sale.tipTotal > 0 ? <p className="mt-3 rounded-xl bg-success-500/10 p-3 font-bold text-success-500">Propina: {formatCOP(sale.tipTotal)}</p> : null}</section>
    <section className="mt-6"><h2 className="font-display text-2xl font-bold">Productos</h2><div className="mt-3 space-y-2">{detail.items.map((item) => <article key={item.id} className="rounded-xl border border-cream-200 bg-cream-50 p-4 shadow-soft"><div className="flex items-start justify-between gap-3"><p className="font-bold">{item.productEmoji} {item.productName}<br /><span className="text-sm font-normal text-choco-600">{item.quantity} × {formatCOP(item.unitPrice)}</span></p><strong>{formatCOP(item.lineTotal)}</strong></div><div className="mt-3 grid grid-cols-2 gap-2 border-t border-cream-200 pt-3 text-sm"><p>Costo histórico<br /><strong>{formatCOP(Math.round(item.lineCost))}</strong></p><p className="text-right">Utilidad<br /><strong className="text-success-500">{formatCOP(item.lineMargin)}</strong></p></div></article>)}</div></section>
    <section className="mt-6"><div className="flex items-center gap-2"><Users className="size-5 text-xp-500" /><h2 className="font-display text-2xl font-bold">Reparto de ganancia</h2></div><div className="mt-3 space-y-2">{detail.allocations.map((allocation) => <article key={allocation.id} className="rounded-xl border border-cream-200 bg-cream-50 p-4 shadow-soft"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{allocation.childEmoji} {allocation.childName}</p><p className="text-xs text-choco-600">{allocation.source === "OWN_SALE" ? "Venta propia" : `Participación familiar${allocation.sharePercent == null ? "" : ` · ${allocation.sharePercent} %`}`}{allocation.reversed ? " · Revertida" : ""}</p></div><strong className="text-success-500">{formatCOP(allocation.totalAmount)}</strong></div><p className="mt-2 text-xs text-choco-600">Margen {formatCOP(allocation.marginAmount)} · propina {formatCOP(allocation.tipAmount)}</p></article>)}{detail.allocations.length === 0 ? <p className="rounded-xl bg-cream-50 p-4 text-sm text-choco-600">No hay reparto asociado.</p> : null}</div></section>
  </main>;
}
